function [] = runInstructions(w,p)
%runInstructions Display instructions on screen for EOWM task
% Written by Sarah 01/2021
continue_message = '\n\n[Press any button to continue.]';
Screen('TextFont',w,'Arial');
Screen('TextSize', w, 25);
cond_colors = p.cue_colors(1,1)>0; %magenta is first color, cyan second color
if cond_colors
    cond_color_names = {'Pink','Blue'};
else
    cond_color_names = {'Blue','Pink'};
end
instructions_list{1} = ['Visual Working Memory Task \nIn this task you will be making judgments from your memory.'... 
    '\nFirst you will be shown a gray dot somewhere on the screen.'...
    '\nThen you will wait for a short delay period (about ' num2str(p.delay_dur) ' seconds).'...
    '\nAfter this delay period, you will see a second gray dot on screen.'...
    '\nYour job is to indicate, by pressing the 1 or 2 button, \nwhether the second dot was counter-clockwise (1) or clockwise (2) from the first dot.' ...
continue_message];
instructions_list{2} = ['You will make your response using the "1" or "2" key \nwhen the second circle is on screen.'...
    '\nAfter you respond, the original circle will reappear.'...
    '\nIt will be green if you were correct, red if you were incorrect, or yellow if you took too long to respond.'...
    '\nYou will be earning points as you go - \n' num2str(p.correct_points) ' points for each correct answer and ' num2str(p.incorrect_points) ' points for each incorrect answer.'...
    '\nAt the end of each run, you will be shown the total points you have earned so far.' ...
continue_message];
instructions_list{3} = ['It is very important that you maintain your fixation on the fixation circle \nthroughout the entire experiment.' ...
    '\nWe will be using eye tracking to make sure that you are trying your best to fixate.' ...
    '\nWe will also give you breaks during the task so that you may rest.'...
continue_message];
instructions_list{4} = ['\nIn this session, you will complete ' num2str(p.total_runs) ' runs of ' num2str(p.ntrials) ' trials each.' ...
    '\nBefore you start each trial, the fixation circle will change color.'...
    '\nThe color of the circle will tell you what type of trial you are doing - ' cond_color_names{1} ' or ' cond_color_names{2} '.' ...
    '\n' cond_color_names{1} ' and ' cond_color_names{2} ' trials have the same rules and your responses to them should be the same.'...
    '\nHowever, ' cond_color_names{2} ' trials will require you to remember more precise information.' ...
    '\nWhen you are ready to continue, you will complete one practice run.'...
    '\nYour performance on this run is not super important - just try your best!' ...
continue_message];
%[nx, ny, textbounds, wordbounds] = DrawFormattedText(win, tstring [, sx][, sy][, color][, wrapat][, flipHorizontal][, flipVertical][, vSpacing][, righttoleft][, winRect])
for i = 1:length(instructions_list)
    instructions = instructions_list{i};
    Screen('FillRect',w,[0 0 0]);
    DrawFormattedText(w,instructions,'center','center',p.fix_color,[],[],[],1.5);
    Screen('Flip',w);
    pause(1);
    resp = 0;
    while resp == 0
        [resp, ~] = checkForResp([p.resp_keys KbName('3#') KbName('4$')], p.esc_key);
    end
    resp = 0;
end

end

